# Numpy
### Basics de Numpy

In [2]:
import numpy as np 
a = np.arange(15).reshape(3,5) # Crear un arreglo de numpy con elementos del 0 al 14. Cambiar la forma a un arreglo de 3x5 
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [7]:
print(a.shape) 
print(a.ndim) # Número de dimensiones
print(a.dtype)
print(a.itemsize) # tamaño del elemento en el arreglo en bytes
print(a.size)

(3, 5)
2
int32
4
15


In [8]:
b = np.array([6,7,8]) # Crear un arreglo de numpy a partir de una lista de python
c = np.array([[1,2],[3,4]], dtype=complex) # Crear un arreglo de numpy con números complejos
ceros = np.zeros((3,4)) # Crear un arreglo de ceros de 3 x 4, tambien se puede usar np.ones((3,4)) 
d = np.arange(10,30,7) # Crear un arreglo de 1 dim, del 10 hasta el 30 con step 7 

In [9]:
e = np.linspace(0,2,9) # Espacio linear. Del 0 al 2, crear un arreglo con espacio uniforme con 9 elementos
x = np.linspace(0, 2*np.pi, 10)
print(x)
f = np.sin(x)
print(f)

[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]
[ 0.00000000e+00  6.42787610e-01  9.84807753e-01  8.66025404e-01
  3.42020143e-01 -3.42020143e-01 -8.66025404e-01 -9.84807753e-01
 -6.42787610e-01 -2.44929360e-16]


In [10]:
c = np.arange(24).reshape(2,3,4)
c = c.reshape(3,2,4) # reshape regresa un nuevo arreglo, los cambios no son in-place
c = c.reshape(3,-1,4) # -1 funciona como comodin, para que la matriz pueda tener todos los datos
c = c.reshape(-1) # Crea una matriz lineal 
c = c.reshape(1,-1) # Arreglo con dos dimensiones, aunque solo tiene un renglón 
c = c.reshape(3,-1) # La forma sería (3,8) 

In [ ]:
d = np.zeros((2,2))
e = d
d[0,0] = 2
print(d)
print(e) # Es por referencia. Si cambiamos d, cambiamos e. Las listas en python funcionan igual. 

## Ejemplos del prof
Broadcasting -> virtualmente propagar un arreglo las veces necesarias para poder comparar 

In [11]:
a = np.array([1,2,3,4]).reshape(1,-1) 
a = np.array([1,3,6]).reshape(-1,1)
''' 
Broadcasting

a = [[1,2,3,4],
    [1,2,3,4],
    [1,2,3,4]]
b = [[1,1,1,1],
    [3,3,3,3],
    [6,6,6,6]]
'''
# Ocurre broadcasting.
# a virtualmente se convierte en un arreglo 3 x 4 y b en 3 x 4 para poder comparar los elementos.
# Las operaciones se hacen elemento a elemento.
c = a==b
d = a*b 
e = a+b
f = a>b

In [12]:
def simple_pred(df, theta): 
    ftr = df.reshape(1,-1)
    pred = ftr >= theta
    return pred

def simple_acc(ftr, outcome, theta): 
    pred = simple_pred(ftr, theta)
    lbl = outcome.reshape(1,-1)
    cmp = pred == lbl
    acc = cmp.mean(axis=1) # mean within each row (over columns)
    return acc

cc = simple_acc(np.array([150.,100.,110.,125.]).reshape(1,-1), np.array([True, True,False,False]).reshape(1,-1),np.array([120.,130.]).reshape(-1,1))
print(cc)

[0.5  0.75]


In [20]:
a = np.array([1.,3.,5.,4.,7.,10.]).reshape((2,3))
print(a)
b = np.array([3.,0.5,2., 8.]).reshape((4,1))
print(b)
c = a * b # No se puede hacer broadcasting por las dimensiones. 
          # Tiene que poder propagar una dimensión completa sobre la otra.

[[ 1.  3.  5.]
 [ 4.  7. 10.]]
[[3. ]
 [0.5]
 [2. ]
 [5. ]]


ValueError: operands could not be broadcast together with shapes (2,3) (4,1) 

argmax() -> regresa el índice del primer elemento max que se encuentra 

